### ISSUE TITLE
Run tests that are not yet added to git

### ISSUE THREAD

**Issue by matveypashkovskiy** [F-Secure/pytest-rts#86]
Steps to reproduce:
1. Create new source file
2. Create a test file for it (do not run `git add`)
3. run `pytest --rts`

Observer behaviour:
- The test won't be executed

Expected behaviour:
- The test is executed

It happens because `git diff --name-only` doesn't list untracked files. Probably we need to add something like: `+ subprocess.check_output("git ls-files --others --exclude-standard".split()).split()` to the end of [the line](https://github.com/F-Secure/pytest-rts/blob/c758da61dc9ad7997e74567f88fbdaa3eb8c8624/pytest_rts/utils/git.py#L51)

**Comment by guotin** [comment]
New test discovery is done for committed changes ("Update phase") where it would be first run and inserted to the mapping database, along with coverage data for a new source file if some test touches it. I guess some extra conditions could be made for running new tests that are not yet added to Git. I'm not sure if parsing untracked files would solve something because a) a new source file has no coverage information and b) new test is not in the database.

**Comment by matveypashkovskiy** [comment]
What if we always run new tests but ignore coverage for those? The process behind this is that I created a bunch of new classes and tests and before the commit, I would like to run all of them to make sure it works. And I expect that modified tests (or tests related to changed source files) and new tests will be executed.

BTW do you use pytest-rts during the development of pytest-rts?

**Comment by matveypashkovskiy** [comment]
covered in #92
